export enum FieldType {
    Adress = "address",
    Date = "date",
    Daterange = "daterange",
    Double = "double",
    Enum = "enum",
    Monetary = "monetary",
    Org = "org",
    People = "people",
    Phone = "phone",
    Set = "set",
    Text = "text",
    Time = "time",
    Timerange = "timerange",
    User = "user",
    Varchar = "varchar",
    VarcharAuto = "varchar_auto",
    VisibleTo = "visible_to",
}
